[window]
opacity = 0.90

[font]
normal = { family = "Terminus", style = "Bold" }
bold = { family = "Terminus", style = "Bold" }
italic = { family = "Ubuntu Mono", style = "Italic" }
bold_italic = { family = "Ubuntu Mono", style = "Bold Italic" }
size = 16
offset.y = 3

[colors]
draw_bold_text_with_bright_colors = true
[colors.primary]
foreground = "#f9f5d7"
background = "#212121"

[colors.bright]
black = "#666666"
white = "#ffffff"
red = "#f14c4c"
green = "#23da8b"
yellow = "#f5f543"
blue = "#3b8eea"
magenta = "#d670d6"
cyan = "#29b8db"

[colors.normal]
black = "#000000"
white = "#e5e5e5"
red = "#cd3131"
green = "#05b572"
yellow = "#e5e510"
blue = "#2472c8"
magenta = "#bc3fbc"
cyan = "#11a8cd"
